### ISSUE TITLE
Compilation on Linux hints

### ISSUE THREAD

**Issue by SpotlightKid** [LuckyResistor/MicroPythonBitmapTool#1]
Hi, nice tool!

Just wanted to let you know that I was able to compile it on Linux (Arch Linux) once I realized it needs Qt 6 and doesn't seem to work with Qt 5.x.

Compilation & installation steps (assuming `qt6-base` package and general build tools, gcc etc. are installed):

```con
git clone https://github.com/LuckyResistor/MicroPythonBitmapTool.git
cd MicroPythonBitmapTool
qmake6
make
install -s MicroPythonBitmapTool ~/bin
```

It would be nice if you could add this information to the readme and/or the page for the app on your website.

**Comment by LuckyResistor** [comment]
Hi,
Sorry for my late reply. Thank you very much for testing and good to know it compiles also on Linux.
I will add these instructions on the next update.
- LR

**Comment by LuckyResistor** [comment]
I added build instructions on the application page, but describe how to install Qt Creator as a development environment. This mainly, because usually Qt 6 is not available on many Linux distributions. By installing Qt using the online installer tool, the user has easy access to the latest versions of the toolkit.
